version: '3.5'

services:
  stock-analyser-api:
    build:
      context: '.'
      dockerfile: ./Dockerfile
    container_name: stock-analyser-api
    ports:
      - "8000:8000"
    volumes:
      - .:/stock-analyser-api:delegated
