site_name: Stock Analyser Project

theme:
  name: "material"

plugins:
- mkdocstrings:
    handlers:
      custom_handler:
        handler_config_option: yes
        options:
          some_config_option: "a"
          other_config_option: 0

nav:
  - Stock Analyser: index.md
  - How-To Guides: how-to-guides.md
  - reference.md
